### ISSUE TITLE
Participant example still need CISCO_SPARK_TOKEN

### ISSUE THREAD

**Issue by guillain** [bernard357/shellbot#22]
If only the constante mention in the header of the script are provided:
```bash
    export CISCO_SPARK_BOT_TOKEN="<token id from Cisco Spark for Developers>"
    export SERVER_URL="http://1a107f21.ngrok.io"
```
The script has an issue to start and request more privilege:
```bash
07:20:15 Unable to handle webhook
07:20:15 Response Code [401] - Authentication credentials were missing or incorrect.
Traceback (most recent call last):
  File "/var/www/shellbot/shellbot/spaces/ciscospark.py", line 749, in register
    for webhook in self.personal_api.webhooks.list():
  File "/usr/lib/python2.7/site-packages/ciscosparkapi/api/webhooks.py", line 158, in list
    for item in items:
  File "/usr/lib/python2.7/site-packages/ciscosparkapi/restsession.py", line 148, in get_items
    for json_page in pages:
  File "/usr/lib/python2.7/site-packages/ciscosparkapi/restsession.py", line 132, in get_pages
    check_response_code(response, erc)
  File "/usr/lib/python2.7/site-packages/ciscosparkapi/utils.py", line 104, in check_response_code
    response=response)
SparkApiError: Response Code [401] - Authentication credentials were missing or incorrect.
07:20:15 Registering webhook to Cisco Spark
```
To solve that it's mandatory to use also another environment token:
```bash
CISCO_SPARK_TOKEN
```
Tks

**Comment by guillain** [comment]
Issue solved since the last update.

Thanks :)
