### ISSUE TITLE
[Escalation example] Issue when Moderator leaves the room

### ISSUE THREAD

**Issue by guillain** [bernard357/shellbot#3]
Sequence to reproduce the issue
1/ Run initally the bot: it will create the room and associate the moderator
2/ Moderator leaves the room from Cisco Spark GUI
3/ Restart shellbot: Impossible to create the webhook and the moderator doesn't come back in the room

Same issue if the the bond(reset=True) is done (l. 284)

To solve the issue, new room name must be set.

Traces:
```bash
14:28:42 Unable to add webhook
14:28:42 Response Code [400] - The request was invalid or cannot be otherwise served. An accompanying error message will explain further.
Traceback (most recent call last):
  File "/var/www/shellbot/shellbot/spaces/ciscospark.py", line 614, in register
    filter='roomId='+self.id)
  File "/usr/lib/python2.7/site-packages/ciscosparkapi/api/webhooks.py", line 199, in create
    json_obj = self._session.post('webhooks', json=post_data)
  File "/usr/lib/python2.7/site-packages/ciscosparkapi/restsession.py", line 187, in post
    check_response_code(response, erc)
  File "/usr/lib/python2.7/site-packages/ciscosparkapi/utils.py", line 104, in check_response_code
    response=response)
SparkApiError: Response Code [400] - The request was invalid or cannot be otherwise served. An accompanying error message will explain further.
14:28:49 Beginning of the sequence
14:28:49 Starting machine
```

**Comment by bernard357** [comment]
@guillain after the tests of this week, do you still experience the issue?

**Comment by guillain** [comment]
hi @bernard357 ,
Effectively issue is solved ;)
Thanks
