### ISSUE TITLE
Multiproessing issue when it's on windows OS

### ISSUE THREAD

**Issue by guillain** [bernard357/shellbot#33]
Hello,

I've issue to run shellbot on Windows OS.
This is apparently due to the multiprocessing library and specific attention to have on its integration.

Below the trace log.
Thanks in advance;)

```bash
C:\Python27\python.exe C:/Users/guillain.sanchez/PycharmProjects/xxx/bot-yml.py
20:16:22 Creating the engine
20:16:25 Creating the engine
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python27\lib\multiprocessing\forking.py", line 380, in main
    prepare(preparation_data)
  File "C:\Python27\lib\multiprocessing\forking.py", line 509, in prepare
    '__parents_main__', file, path_name, etc
  File "C:\Users\guillain.sanchez\PycharmProjects\xxx\bot-yml.py", line 30, in <module>
    CmdSearch(),
  File "c:\users\guillain.sanchez\documents\__dev\python\shellbot\shellbot\engine.py", line 257, in __init__
    self.context = context if context else Context()
  File "c:\users\guillain.sanchez\documents\__dev\python\shellbot\shellbot\context.py", line 50, in __init__
    self.values = Manager().dict()
  File "C:\Python27\lib\multiprocessing\__init__.py", line 99, in Manager
    m.start()
  File "C:\Python27\lib\multiprocessing\managers.py", line 524, in start
    self._process.start()
  File "C:\Python27\lib\multiprocessing\process.py", line 130, in start
    self._popen = Popen(self)
  File "C:\Python27\lib\multiprocessing\forking.py", line 258, in __init__
    cmd = get_command_line() + [rhandle]
  File "C:\Python27\lib\multiprocessing\forking.py", line 358, in get_command_line
    is not going to be frozen to produce a Windows executable.''')
RuntimeError: 
            Attempt to start a new process before the current process
            has finished its bootstrapping phase.

            This probably means that you are on Windows and you have
            forgotten to use the proper idiom in the main module:

                if __name__ == '__main__':
                    freeze_support()
                    ...

            The "freeze_support()" line can be omitted if the program
            is not going to be frozen to produce a Windows executable.
Traceback (most recent call last):
  File "C:/Users/guillain.sanchez/PycharmProjects/xxx/bot-yml.py", line 30, in <module>
    CmdSearch(),
  File "c:\users\guillain.sanchez\documents\__dev\python\shellbot\shellbot\engine.py", line 257, in __init__
    self.context = context if context else Context()
  File "c:\users\guillain.sanchez\documents\__dev\python\shellbot\shellbot\context.py", line 50, in __init__
    self.values = Manager().dict()
  File "C:\Python27\lib\multiprocessing\__init__.py", line 99, in Manager
    m.start()
  File "C:\Python27\lib\multiprocessing\managers.py", line 528, in start
    self._address = reader.recv()
EOFError

Process finished with exit code 1
```

**Comment by bernard357** [comment]
@guillain, from your log the understanding is that you need to change code in `bot-yml.py` so that the call to function `CmdSearch()` is performed after the following line:

`if __name__ == '__main__':`

It seems that multiprocessing in Windows involves multiple loads of the module in memory. So with the addition of the test above you guarantee that your code is run only once, even if it has been loaded multiple times in memory. In other words:

    if __name__ == '__main__':
        CmdSearch()

You get the idea...

**Comment by bernard357** [comment]
@guillain as per our discussion of today, examples coming with shellbot have been all updated as well. Thanks!
