### ISSUE TITLE
Sequences associated to step are broken

### ISSUE THREAD

**Issue by guillain** [bernard357/shellbot#6]
Hi,
I've issue to add the dedicated sequences to step.
Not sure if it's supported right now so if not that cna be an improvement request ;)

My code is based on escalation example where I want one sequence by step.

example:
```bash 
myAA = Input(bot=bot, question="Input A-A")
myAB = Input(bot=bot, question="Input A-B")

myBA = Input(bot=bot, question="Input B-A")
myBB = Input(bot=bot, question="Input B-B")

bot.load_command('shellbot.commands.step') # progress to next step of process
steps = bot.get('process.steps', [])
steps[0]['machine'] = Sequence(machines=[myAA,myAB])
steps[1]['machine'] = Sequence(machines=[myBA,myBB])

from shellbot.machines import Steps
bot.machine = Steps(bot=bot, steps=steps)
```

Log when second step is reached:
```bash
13:08:38 Handling: step
13:08:38 Transitioning: completed => running
13:08:38 Moving to next step of the process
13:08:38 - triggering step #1
13:08:38 Bot says: New state: Level 2
13:08:38 - pushing message to mouth queue
13:08:38 Bot says:
13:08:38 - pushing message to mouth queue
13:08:38 Adding moderators
13:08:38 Adding participants
13:08:38 Resetting sequence
13:08:38 Resetting machine to 'begin'
13:08:38 Speaker is working on 15
13:08:38 Posting message
13:08:38 - text: New state: Level 2
13:08:38 - roomId: Y2lzY29zcGFyazovL3VzL1JPT00vYWZlNzdlYzAtNTk5Ni0xMWU3LTg5MzAtZWZhYTI5ZDZhZmE0
13:08:38 Resetting machine to 'begin'
13:08:38 Bot says: Sorry, I do not know how to handle 'step'
13:08:38 - pushing message to mouth queue
13:08:38 - invalid format, thrown away
13:08:38 daemonic processes are not allowed to have children
Traceback (most recent call last):
  File "/var/www/shellbot/shellbot/listener.py", line 109, in work
    self.process(item)
  File "/var/www/shellbot/shellbot/listener.py", line 192, in process
    raise ValueError(feedback)
ValueError: daemonic processes are not allowed to have children
13:08:38 https://api.ciscospark.com:443 "POST /v1/messages HTTP/1.1" 200 339
13:08:38 - done
```

**Comment by bernard357** [comment]
Hello Guillain, thanks for the comprehensive issue description. The message `daemonic processes are not allowed to have children` comes from the creation of the parent process, when `p.dameon = True` is used. I will investigate and refine further.

**Comment by guillain** [comment]
Hi,
In the last shellbot version the issue is solve.
Thanks a lot ;)
